"""creating users

Revision ID: 8f9b7928ae6e
Revises: 34ff8feed7b0
Create Date: 2020-11-03 22:32:03.503994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9b7928ae6e'
down_revision = '34ff8feed7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_volume')
    # ### end Alembic commands ###
